metadata:
  run_name: 'PAEInputFlattened_large_kernel_stft'
  log_dir: 'logs'
  logging: True

dataset_config:
  dataset: 'audio_dataset'
  dataset_root: 'data/test'
  resume: null

training_config:
  num_epochs: 50
  batch_size: 10
  batch_size_validation: 10
  optimizer: 'adam'
  optimizer_lr: 0.0001
  optimizer_momentum: 0.9
  optimizer_weight_decay: 0.001
  optimizer_float_16: False
  lr_scheduler: 'poly'
  lr_scheduler_power: 0.9
  ckpt_save_dir: 'logs/checkpoints'

model_config:
  experiment_name: 'PAEInputFlattenedModel'
  model_name: 'pae_flat'
  input_channels: 1
  intermediate_channels: 3 # 16
  embedding_channels: 6
  kernel_size: 51
  time_range: 32000
  window: 2.0
  dilation: 10

worker_config:
  workers: 0
  workers_validation: 0