metadata:
  run_name: 'PAEWave_earlystopping'
  log_dir: 'logs'
  logging: True

dataset_config:
  dataset: 'audio_dataset'
  dataset_root: 'data/test'
  resume: null

training_config:
  num_epochs: 200
  batch_size: 10
  batch_size_validation: 10
  optimizer: 'adam'
  optimizer_lr: 0.001
  optimizer_momentum: 0.85
  optimizer_weight_decay: 0.002
  optimizer_float_16: False
  lr_scheduler: 'poly'
  lr_scheduler_power: 0.9
  ckpt_save_dir: 'logs/checkpoints'

model_config:
  experiment_name: 'PAEWaveModel'
  model_name: 'pae_wave'
  input_channels: 1
  intermediate_channels: 32
  embedding_channels: 16
  kernel_size: 50
  time_range: 32000
  window: 2.0
  dilation: 2 # Not actually used in wavenet
  residual_channels: 16 # NEW for wavenet
  dilation_channels: 32  # NEW for wavenet
  skip_channels: 16  # NEW for wavenet
  layers: 4 # NEW for wavenet 
  blocks: 2   # NEW for wavenet
  classes: 16 # NEW for wavenet

worker_config:
  workers: 7
  workers_validation: 7