metadata:
  run_name: 'PAEDeep'
  log_dir: 'logs'
  logging: True

dataset_config:
  dataset: 'audio_dataset'
  dataset_root: 'data/test'
  resume: null

training_config:
  num_epochs: 100
  batch_size: 5
  batch_size_validation: 5
  optimizer: 'adam'
  optimizer_lr: 0.001
  optimizer_momentum: 0.9
  optimizer_weight_decay: 0.001
  optimizer_float_16: False
  lr_scheduler: 'poly'
  lr_scheduler_power: 0.9
  ckpt_save_dir: 'logs/checkpoints'

model_config:
  experiment_name: 'PAEDeepModel'
  model_name: 'pae_deep'
  input_channels: 1
  intermediate_channels2: 2 # 16
  intermediate_channels1: 1 # TODO: remove
  embedding_channels: 3
  kernel_size: 50
  time_range: 32000
  window: 2.0
  dilation: 5

worker_config:
  workers: 7
  workers_validation: 7