metadata:
  run_name: 'PAElla_test'
  log_dir: 'logs'
  logging: True

dataset_config:
  dataset: 'audio_dataset'
  dataset_root: 'data/test'
  resume: null

training_config:
  num_epochs: 120
  batch_size: 5
  batch_size_validation: 5
  optimizer: 'adam'
  optimizer_lr: 0.0005
  optimizer_momentum: 0.9
  optimizer_weight_decay: 0.001
  optimizer_float_16: False
  lr_scheduler: 'poly'
  lr_scheduler_power: 0.9
  ckpt_save_dir: 'logs/checkpoints'

model_config:
  experiment_name: 'PAEllaModel'
  model_name: 'paella'
  input_channels: 1
  intermediate_channels: 1 # 16
  embedding_channels: 8
  kernel_size: 51
  time_range: 32000
  window: 2.0
  dilation: 1
  safe_signals: True

worker_config:
  workers: 0
  workers_validation: 0